routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'KbController@welcome');

Auth::routes();

// Route::get('/login', function(){
// 	return view('errors.404');
// })->name('login');

// Route::get('register', function(){
// 	return view('errors.404');
// });

Route::get('/home', 'HomeController@index')->name('home');

Route::get('/playlists', 'KbController@playlists')->name('playlists');

Route::get('/gallery', 'KbController@gallery')->name('gallery');

Route::get('artistPage/{name}', 'KbController@getArtist');

Route::get('/contactUs', function () {
	return view('pages.contactUs');
})->name('contact');

Route::get('/about', function () {
	return view('pages.about');
})->name('about');

Route::post('/contactUs', 'KbController@contactUs')->name('contactUs');

Route::post('newArtist', 'KobotuneController@newArtist')->name('newArtist');

Route::post('/newMusic', 'KobotuneController@newMusic')->name('newMusic');

Route::get('/kobotune_lounge', 'KobotuneController@index');

Route::get('/kobotune_lounge/artists/{id}', 'KobotuneController@getArtist');

Route::delete('/kobotune_lounge/artists/{id}', 'KobotuneController@deteleMusic')->name('deleteMusic');

Route::post('/subscribe', 'KbController@subscribe');

Route::group(['prefix' => 'kobotune_lounge'], function () {
	Route::Resource('playlist', 'PlaylistController');
});

resources/views/admin/artist.blade.php
@extends('layouts.index')

@section('title')

{{$artist->name}}

@endsection


@section('content')

@if(Session::has('success'))
    <div class="alert alert-success">
      New Artist Added Successfully!.
    </div>
@endif

@if(Session::has('deteted'))
    <div class="alert alert-danger">
      Song deleted Successfully!.
    </div>
@endif

<div class="row" style="margin-left: 50px;">
    <a href="#" data-toggle="modal" data-target="#AddNewArtistSongModal" class="col-xl-3 col-sm-6 mb-3">
      <div class="card text-white bg-primary o-hidden h-100">
        <div class="card-body">
          <div class="card-body-icon">
            {{-- <i class="fas fa-fw fa-comments"></i> --}}
          </div>
          <div class="mr-5 text-center h4">Add New Song</div>
        </div>
      </div>
    </a>
    <div class="col-xl-3 col-sm-6 mb-3">
      <div class="card text-white bg-success o-hidden h-100">
        <div class="card-body">
          <div class="card-body-icon">
            {{-- <i class="fas fa-fw fa-shopping-cart"></i> --}}
          </div>
          @if($artist->music)
          <div class="mr-5 text-center h4">{{count($artist->music)}}</div>
          @else
          <div class="mr-5 text-center h4">0</div>
          @endif
        </div>
        <a class="card-footer text-white clearfix small z-1" href="#">
          <span class="float-left">Total Music</span>
          <span class="float-right">
            <i class="fas fa-angle-right"></i>
          </span>
        </a>
      </div>
    </div>
  </div>

  <!-- DataTables Example -->
          @if($artist)
          <div class="card mb-3">
            <div class="card-header">
              <i class="fas fa-table"></i>
              {{$artist->stage_name}} Songs</div>
            <div class="card-body">
              <div class="table-responsive">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                  <thead>
                    <tr>
                      <th>Song Title</th>
                      <th>Music Link</th>
                      <th>Action</th>
                    </tr>
                  </thead>
                  <tfoot>
                    <tr>
                      <th>Song Title</th>
                      <th>Music Link</th>
                      <th>Action</th>
                    </tr>
                  </tfoot>
                  <tbody>
                    	@foreach($artist->music as $music)
                    <tr>
                      <td>{{$music->music_name}}</a></td>
                      <td><a href="{{$music->music_link}}">{{$music->music_link}}</a></td>
                      <td>
                      	<form action="{{route('deleteMusic', $music->id)}}" method="post">
                      		@csrf
                      		@method('delete')
                      		<input type="hidden" name="id" value="{{$music->id}}">
                      		<button type="submit" class="text-capitalize btn btn-danger">delete</button>
                      	</form>
                      </td>
                    </tr>
                      	@endforeach
                  </tbody>
                </table>
              </div>
            </div>
          </div>
          @endif

  <!-- Add new artist Modal -->
<div class="modal fade" id="AddNewArtistSongModal" tabindex="-1" role="dialog" aria-labelledby="AddNewArtistSongModal" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="AddNewArtistSongModal">Add New Artist</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <div class="login-form">
          <form action="{{route('newMusic')}}" method="post" enctype="multipart/form-data">
            @csrf
            <div class="form-group">
                <label for="name">Song Title</label>
                <input type="text" name="name" class="form-control" id="name" placeholder="Song title" required>
            </div>
            <div class="form-group">
                <label for="image">Song Art/image</label>
                <input type="file" class="form-control" id="image" name="image" accept="image/*" required>
            </div>
            <div class="form-group">
                <label for="music_link">Music Link</label>
                <input type="text" name="music_link" class="form-control" id="music_link" placeholder="Music Link eg http://www.soundcloud.com/muisicname" required>
            </div>
            <input type="hidden" name="artist_id" value="{{$artist->id}}">
            <div class="form-group">
              <button type="submit" class="btn btn-info oneMusic-btn mt-30 text-right">Submit</button>
            </div>
          </form>
      </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

@endsection

resources/views/admin/index.blade.php
@extends('layouts.index')


@section('title')

{{"Dashboard"}}

@endsection

@section('content')

<div class="container-fluid">
	<!-- Breadcrumbs-->
	<ol class="breadcrumb">
		<li class="breadcrumb-item">
			<a href="#">Dashboard</a>
		</li>
		<li class="breadcrumb-item active">Overview</li>
	</ol>

	@if(Session::has('success'))
		<div class="alert alert-success">
			{{session('success')}}
		</div>
	@endif

	@if($errors->any())
	@foreach ($errors->all() as $error)
		<div class="alert alert-danger">
			{{$error}}
		</div>
	@endforeach
	@endif

	<!-- Icon Cards-->
	<div class="row">
		<a href="#" data-toggle="modal" data-target="#AddNewArtistModal" class="col-xl-3 col-sm-6 mb-3">
			<div class="card text-white bg-primary o-hidden h-100">
				<div class="card-body">
					<div class="card-body-icon">
						{{-- <i class="fas fa-fw fa-comments"></i> --}}
					</div>
					<div class="mr-5 text-center h4">Add New Artist</div>
				</div>
			</div>
		</a>
		<a href="#" data-toggle="modal" data-target="#AddNewPlaylistModal" class="col-xl-3 col-sm-6 mb-3">
			<div class="card text-white bg-warning o-hidden h-100">
				<div class="card-body">
					<div class="card-body-icon">
						<i class="fas fa-fw fa-list"></i>
					</div>
					<div class="mr-5 text-center h4">Add Playlist</div>
				</div>
			</div>
		</a>
		<div class="col-xl-3 col-sm-6 mb-3">
			<div class="card text-white bg-success o-hidden h-100">
				<div class="card-body">
					<div class="card-body-icon">
						{{-- <i class="fas fa-fw fa-shopping-cart"></i> --}}
					</div>
					<div class="mr-5 text-center h4">690</div>
				</div>
				<a class="card-footer text-white clearfix small z-1" href="#">
					<span class="float-left">Total Audio</span>
					<span class="float-right">
						<i class="fas fa-angle-right"></i>
					</span>
				</a>
			</div>
		</div>
		<div class="col-xl-3 col-sm-6 mb-3">
			<div class="card text-white bg-danger o-hidden h-100">
				<div class="card-body">
					<div class="card-body-icon">
						<i class="fas fa-fw fa-life-ring"></i>
					</div>
					<div class="mr-5 text-center h4">479</div>
				</div>
				<a class="card-footer text-white clearfix small z-1" href="#">
					<span class="float-left">Total Video</span>
					<span class="float-right">
						<i class="fas fa-angle-right"></i>
					</span>
				</a>
			</div>
		</div>
	</div>
	<!-- playlists -->
	@if($playlists)
	<div class="card mb-3">
		<div class="card-header">
			<i class="fas fa-table"></i>
			Kobotune Playlists
		</div>
		<div class="card-body">
			<div class="table-responsive">
				<table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
					<thead>
						<tr>
							<th>Playlist Name</th>
							<th>Playlist Genre</th>
							<th>Playlist Image</th>
							<th>Playlist URL</th>
						</tr>
					</thead>
					<tfoot>
						<tr>
							<th>Playlist Name</th>
							<th>Playlist Genre</th>
							<th>Playlist Image</th>
							<th>Playlist URL</th>
						</tr>
					</tfoot>
					<tbody>
						@foreach($playlists as $playlist)
						<tr>
							<td><a href="#">{{$playlist->name}}</a></td>
							<td>{{$playlist->genre}}</td>
							<td><img src="{{$playlist->imageUrl()}}" width="50px" height="50px" alt="{{$playlist->name}}"></td>
							<td>{{$playlist->url}}</td>
						</tr>
						@endforeach
					</tbody>
				</table>
			</div>
		</div>
	</div>
	@endif
	{{-- artists --}}
	@if($artists)
	<div class="card mb-3">
		<div class="card-header">
			<i class="fas fa-table"></i>
			Kobotune Artists
		</div>
		<div class="card-body">
			<div class="table-responsive">
				<table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
					<thead>
						<tr>
							<th>Name</th>
							<th>Stage Name</th>
							<th>Music Type</th>
							<th>Music Count</th>
						</tr>
					</thead>
					<tfoot>
						<tr>
							<th>Name</th>
							<th>Stage Name</th>
							<th>Music Type</th>
							<th>Music Count</th>
						</tr>
					</tfoot>
					<tbody>
							@foreach($artists as $artist)
						<tr>
							<td><a href="/kobotune_lounge/artists/{{$artist->id}}">{{$artist->name}}</a></td>
							<td>{{$artist->stage_name}}</td>
							<td>{{$artist->music_type}}</td>
							@if($artist->music)
							<td>{{count($artist->music)}}</td>
							@else
							<td>0</td>
							@endif
						</tr>
								@endforeach
					</tbody>
				</table>
			</div>
		</div>
	</div>
	@endif

</div>
<!-- /.container-fluid -->

<!-- Add new artist Modal -->
<div class="modal fade" id="AddNewArtistModal" tabindex="-1" role="dialog" aria-labelledby="AddNewArtistModal" aria-hidden="true">
	<div class="modal-dialog modal-dialog-centered" role="document">
		<div class="modal-content">
			<div class="modal-header">
				<h5 class="modal-title" id="AddNewArtistModal">Add New Artist</h5>
				<button type="button" class="close" data-dismiss="modal" aria-label="Close">
					<span aria-hidden="true">&times;</span>
				</button>
			</div>
			<div class="modal-body">
				<div class="login-form">
					<form action="{{route('newArtist')}}" method="post" enctype="multipart/form-data">
						@csrf
						<div class="form-group">
								<label for="name">Artist Name</label>
								<input type="text" name="name" class="form-control" id="name" placeholder="Artist Full Name" required>
						</div>
						<div class="form-group">
								<label for="stage_name">Artist Stage Name</label>
								<input type="text" name="stage_name" class="form-control" id="stage_name" placeholder="Artist Stage Name" required>
						</div>
						<div class="form-group">
								<label for="image">Artist Image</label>
								<input type="file" class="form-control" id="image" name="image" accept="image/*" required>
						</div>
						<div class="form-group">
								<label for="music_type">Artist Music Type</label>
								<input type="text" name="music_type" class="form-control" id="music_type" placeholder="Artist Music Type" required>
						</div>
						<div class="form-group">
								<label for="bio">Artist Little Bio</label>
								<textarea class="form-control" name="bio" id="bio" required></textarea>
						</div>
						<div class="form-group">
							<button type="submit" class="btn btn-info oneMusic-btn mt-30 text-right">Submit</button>
						</div>
					</form>
			</div>
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
			</div>
		</div>
	</div>
</div>


				<!-- Add new artist Modal -->
<div class="modal fade" id="AddNewPlaylistModal" tabindex="-1" role="dialog" aria-labelledby="AddNewPlaylistModal" aria-hidden="true">
	<div class="modal-dialog modal-dialog-centered" role="document">
		<div class="modal-content">
			<div class="modal-header">
				<h5 class="modal-title" id="AddNewArtistModal">Add New Playlist</h5>
				<button type="button" class="close" data-dismiss="modal" aria-label="Close">
					<span aria-hidden="true">&times;</span>
				</button>
			</div>
			<div class="modal-body">
				<div class="login-form">
					<form action="{{route('playlist.store')}}" method="post" enctype="multipart/form-data">
						@csrf
						<div class="form-group">
							<label for="name">Playlist Name</label>
							<input type="text" name="name" class="form-control" id="name" placeholder="Playlist Full Name" required>
						</div>
						<div class="form-group">
							<label for="music_type">Playlist Music Genre</label>
							<input type="text" name="music_type" class="form-control" id="music_type" placeholder="Playlist Music Genre" required>
						</div>
						<div class="form-group">
							<label for="url">Playlist URL</label>
							<input type="text" class="form-control" id="url" name="url" placeholder="https://open.spotify.com/playlist/37i9dQZF1DWYkaDif7Ztbp" required>
						</div>
						<div class="form-group">
							<label for="image">Playlist Image</label>
							<input type="file" class="form-control" id="image" name="image" accept="image/*" required>
						</div>
						<div class="form-group mt-5 text-right">
							<button type="submit" class="btn btn-info oneMusic-btn mt-30 text-right">Submit</button>
						</div>
					</form>
			</div>
			</div>
		</div>
	</div>
</div>

@endsection

resources/views/admin/modals.blade.php
<!-- Add new artist Modal -->
<div class="modal fade" id="AddNewArtistModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalCenterTitle">Add New Artist</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <div class="login-form">
          <form action="#" method="post">
            <div class="form-group">
                <label for="exampleInputEmail1">Email address</label>
                <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Enter E-mail">
                <small id="emailHelp" class="form-text text-muted"><i class="fa fa-lock mr-2"></i>We'll never share your email with anyone else.</small>
            </div>
            <div class="form-group">
                <label for="exampleInputPassword1">Password</label>
                <input type="password" class="form-control" id="exampleInputPassword1" placeholder="Password">
            </div>
            <button type="submit" class="btn oneMusic-btn mt-30">Login</button>
          </form>
      </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Save changes</button>
      </div>
    </div>
  </div>
</div>